### ISSUE TITLE
Unrecognized command-line input arguments: 'token, labels'.

### ISSUE THREAD

**Issue by okainov** [SanderKnape/github-runner#9] opened 2020-09-02 08:52 UTC
When I use this Docker image, I'm getting an error during registration

```
Requesting token at 'https://api.github.com/repos/<myorg>/<myrepo>/actions/runners/registration-token'
Unrecognized command-line input arguments: 'token, labels'. For usage refer to: .\config.cmd --help or ./config.sh --help
--------------------------------------------------------------------------------
| ____ _ _ _ _ _ _ _ _ |
| / ___(_) |_| | | |_ _| |__ / \ ___| |_(_) ___ _ __ ___ |
| | | _| | __| |_| | | | | '_ \ / _ \ / __| __| |/ _ \| '_ \/ __| |
| | |_| | | |_| _ | |_| | |_) | / ___ \ (__| |_| | (_) | | | \__ \ |
| \____|_|\__|_| |_|\__,_|_.__/ /_/ \_\___|\__|_|\___/|_| |_|___/ |
| |
| Self-hosted runner registration |
| |
--------------------------------------------------------------------------------
# Authentication
Invalid configuration provided for token. Terminating unattended configuration.
An error occurred: Not configured
```

**Comment by SanderKnape** [comment] 2020-09-15 08:16
Hi, I'm not able to reproduce this issue. Can you give more information on what you did to get this error?

**Comment by okainov** [comment] 2020-09-15 10:30
I was running the image inside K8S via Rancher... Nothing really special, I took the k8s config from some blog post (presumably yours?)...

**Comment by jasonhancock** [comment] 2020-09-25 18:33
We ran into this issue as well when we weren't specifying any additional labels to add to the runner. I think the fix is to put the `${RUNNER_LABELS}` variable in quotes in the entrypoint.sh script: https://github.com/SanderKnape/github-runner/blob/master/entrypoint.sh#L24

**Comment by SanderKnape** [comment] 2020-09-28 09:12
Thanks for raising this issue! I just pushed a fix - I added quotes around the variables.

**Closed as completed by SanderKnape** 2020-09-28 09:12 UTC
